### ISSUE TITLE
前端部署的时候非常慢

### ISSUE THREAD

**Issue by xianxian0703** [Rynxiao/rap2-docker#1]
Step 2/9 : MAINTAINER wuxian
 ---> Running in ccbbcebc6d1e
 ---> 2afb75c6acdd
Removing intermediate container ccbbcebc6d1e
Step 3/9 : RUN mkdir -p /home/rap2-dolores
 ---> Running in 7b083512bd0f

 ---> 9f6ea9c94903
Removing intermediate container 7b083512bd0f
Step 4/9 : WORKDIR /home/rap2-dolores
 ---> cc23fe041849
Removing intermediate container 842af7dd7548
Step 5/9 : COPY . /home/rap2-dolores
 ---> 3a64b5f56b95
Removing intermediate container b9e2f492fab3
Step 6/9 : RUN npm install -g http-server
 ---> Running in fa9488cfac21

/usr/local/bin/http-server -> /usr/local/lib/node_modules/http-server/bin/http-server
/usr/local/bin/hs -> /usr/local/lib/node_modules/http-server/bin/http-server
+ http-server@0.11.1
added 25 packages in 72.781s
 ---> c4d389ddaf69
Removing intermediate container fa9488cfac21
Step 7/9 : RUN npm install --unsafe-perm -g node-sass
 ---> Running in b03904c656e6

一直卡在这，怎么破？

**Comment by Rynxiao** [comment]
@xianxian0703 貌似你的网不是一般的慢呀，能够fq的话尝试FQ之后再试试
