### ISSUE TITLE
解决 http-server 刷新页面404

### ISSUE THREAD

**Issue by zisheng-ai** [Rynxiao/rap2-docker#3]
参考：https://github.com/indexzero/http-server/issues/318#issuecomment-289059647

### 1. 修改 Dockerfile：

```diff
+ RUN npm set registry https://registry.npm.taobao.org
- RUN npm install -g http-server
+ RUN npm install -g spa-http-server
```

### 2. 修改 `docker-compose.yml`:

```diff
- command: /bin/sh -c 'http-server ./build -s -p 8081'
+ command: /bin/sh -c 'http-server ./build -s -p 8081 --push-state'
```

**Comment by Rynxiao** [comment]
确实会有这样的问题，在第二个版本中，我已经将所有的代码全去掉了，改用nginx做web服务器，只需要使用docker-compose就可以启动所有服务了，详情可以参看 `tag 2.0.0`
